# Generated by Django 4.1.7 on 2023-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHGovSchemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=300)),
                ('Jobtitle', models.CharField(max_length=300)),
                ('Eligibility', models.CharField(max_length=600)),
                ('levelOfEdu', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=800)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('entryLevel', models.CharField(max_length=300)),
            ],
        ),
    ]
