# Generated by Django 4.1.7 on 2023-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHGovSchemes', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JobDes',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
