# Generated by Django 4.1.7 on 2023-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHGovSchemes', '0005_intership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathontitle', models.CharField(max_length=200)),
                ('Organizer', models.CharField(max_length=200)),
                ('HackDesc', models.CharField(max_length=700)),
                ('Startdate', models.CharField(max_length=200)),
                ('Enddate', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=400)),
                ('Link', models.CharField(max_length=1000)),
            ],
        ),
    ]
